### PR TITLE
Feature 2 is developed please review

### PR DESCRIPTION
**Pull request by emperorsudheer**
Feature 2 is developed please review

### CODE REVIEW

**Comment by sudheerkonda9** [comment]
Check Once again

**Comment by emperorsudheer** [comment]
> Check Once again

Yes checked once again , it seems good

**Comment by sudheerkonda9** [comment]
> > Check Once again
> 
> Yes checked once again , it seems good

few more code is missing add forget password feature too

**Comment by emperorsudheer** [comment]
> > > Check Once again
> > 
> > 
> > Yes checked once again , it seems good
> 
> few more code is missing add forget password feature too

Added the feature you asked forget password

**Review by sudheerkonda9 — APPROVED** [review]
Every thing is good approve

**Pull request merged**
